### ISSUE TITLE
Is this going to work only with java17, I tried and getting error as " org/springframework/boot/SpringApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0 "

### ISSUE THREAD

**Issue by mazaharulhq** [robtimus/obfuscation-spring#3]
I am getting below error when I add this obfuscation-spring-starter project in my pom file.

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/SpringApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.voicera.obfuscation.ObfuscationApplication.main(ObfuscationApplication.java:10)

**Comment by robtimus** [comment]
When I wanted to add support for Spring Boot 3.x, I had to make some changes because I used bean validation inside the code, and Spring Boot 3.x uses the `jakarta` package prefix instead of the old `javax` package prefix. That also meant that I had to switch to Java 17, because that's what Spring Boot 3.x requires. I released this as version [2.0](https://github.com/robtimus/obfuscation-spring/releases/tag/2.0) because it was a breaking change. See the release notes for more information.

The good news is that I still actively maintain version 1.x. This still works with Spring Boot 2.x and Java 8. The current version is [1.3.2](https://github.com/robtimus/obfuscation-spring/releases/tag/1.3.2), but I plan on releasing a new security fix soon (only bumping the Spring Boot version to 2.7.12). You don't have to wait on that, as long as you use Spring Boot 2.7.12 yourself.

**Comment by robtimus** [comment]
FYI, version 1.3.3 has just been released which depends on Spring Boot 2.7.12.

**Comment by mazaharulhq** [comment]
That worked and I amble to run the app. But now the questions is how to use code obfuscation for controller methods. I put annotation and do not see any difference when I decompile the class file.

**Comment by robtimus** [comment]
Let's handle that in your other issue (#4)
